// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwNw-X014Ao7IftSY_c9sBpgzmToz_4Po',
    appId: '1:197258925977:web:579325c744daa53f116508',
    messagingSenderId: '197258925977',
    projectId: 'chefcook-flutter',
    authDomain: 'chefcook-flutter.firebaseapp.com',
    storageBucket: 'chefcook-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGWiC6gUxCYabEAe7pp_SD1BFt-l51ll8',
    appId: '1:197258925977:android:913c8d604a9d8c80116508',
    messagingSenderId: '197258925977',
    projectId: 'chefcook-flutter',
    storageBucket: 'chefcook-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUoBFfspnEhO1c7EXrX8IeQbLBfmsZJsU',
    appId: '1:197258925977:ios:45e7323e464b22d8116508',
    messagingSenderId: '197258925977',
    projectId: 'chefcook-flutter',
    storageBucket: 'chefcook-flutter.appspot.com',
    iosBundleId: 'com.example.chefcook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUoBFfspnEhO1c7EXrX8IeQbLBfmsZJsU',
    appId: '1:197258925977:ios:45e7323e464b22d8116508',
    messagingSenderId: '197258925977',
    projectId: 'chefcook-flutter',
    storageBucket: 'chefcook-flutter.appspot.com',
    iosBundleId: 'com.example.chefcook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwNw-X014Ao7IftSY_c9sBpgzmToz_4Po',
    appId: '1:197258925977:web:57cbee5c6cb21716116508',
    messagingSenderId: '197258925977',
    projectId: 'chefcook-flutter',
    authDomain: 'chefcook-flutter.firebaseapp.com',
    storageBucket: 'chefcook-flutter.appspot.com',
  );

}